sonar.projectKey=frontend
sonar.projectName=Leapmentor Frontend
sonar.projectVersion=0.0.0

sonar.sources=src
sonar.exclusions=node_modules/**,dist/**,coverage/**

sonar.host.url=http://localhost:9000
sonar.sourceEncoding=UTF-8

# Test coverage configuration
sonar.tests=src
sonar.test.inclusions=**/*.test.jsx,**/*.test.js
sonar.javascript.lcov.reportPaths=coverage/lcov.info
