sonar.projectKey=frontend
sonar.projectName=Leapmentor Frontend
sonar.projectVersion=0.0.0

sonar.sources=src
sonar.exclusions=node_modules/**,dist/**,coverage/**,src/**/*.test.jsx,src/**/*.test.js,src/test/**

sonar.host.url=http://localhost:9000
sonar.sourceEncoding=UTF-8
