sonar.projectKey=frontend
sonar.projectName=Leapmentor Frontend
sonar.projectVersion=1.0.0

sonar.sources=src
sonar.exclusions=node_modules/**,dist/**,coverage/**

sonar.host.url=http://localhost:9000
sonar.token=squ_8c6eadf252b0d814d1a8cb8061483f54f1aa3ad8
sonar.sourceEncoding=UTF-8

# Test coverage configuration
sonar.tests=src
sonar.test.inclusions=**/*.test.ts,**/*.test.tsx,**/*.test.jsx,**/*.test.js
sonar.typescript.tsconfigPath=tsconfig.json
sonar.javascript.lcov.reportPaths=coverage/lcov.info
